color0 #42474e
color1 #ffb4ab
color2 #9acbfa
color3 #b9c8da
color4 #d2bfe7
color5 #9acbfa
color6 #b9c8da
color7 #e0e2e8
color8 #8c9198
color9 #ffb4ab
color10 #9acbfa
color11 #b9c8da
color12 #d2bfe7
color13 #9acbfa
color14 #b9c8da
color15 #e0e2e8

cursor                #e0e2e8
cursor_text_color     #101418
background            #101418
foreground            #e0e2e8
selection_foreground  #c2c7cf
selection_background  #42474e
active_border_color   #9acbfa
inactive_border_color #42474e
url_color             #9acbfa

active_tab_foreground   #003352
active_tab_background   #9acbfa
inactive_tab_foreground #c2c7cf
inactive_tab_background #42474e
cursor_trail_color      #c2c7cf
