[colors.primary]
background = '#0e1416'
foreground = '#dee3e5'

[colors.cursor]
text = '#0e1416'
cursor = '#dee3e5'

[colors.vi_mode_cursor]
text = '#0e1416'
cursor = '#83d2e4'

[colors.search.matches]
foreground = '#3f484b'
background = '#bdc5eb'

[colors.search.focused_match]
foreground = '#3f484b'
background = '#83d2e4'

[colors.footer_bar]
foreground = '#3f484b'
background = '#dee3e5'

[colors.hints.start]
foreground = '#3f484b'
background = '#b2cbd1'

[colors.hints.end]
foreground = '#3f484b'
background = '#b2cbd1'

[colors.selection]
text = '#bfc8cb'
background = '#3f484b'


[colors.normal]
black   = '#3f484b'
red     = '#ffb4ab'
green   = '#83d2e4'
yellow  = '#b2cbd1'
blue    = '#bdc5eb'
magenta = '#83d2e4'
cyan    = '#b2cbd1'
white   = '#dee3e5'


[colors.bright]
black   = '#899295'
red     = '#ffb4ab'
green   = '#83d2e4'
yellow  = '#b2cbd1'
blue    = '#bdc5eb'
magenta = '#83d2e4'
cyan    = '#b2cbd1'
white   = '#dee3e5'


[colors.dim]
black   = '#3f484b'
red     = '#ffb4ab'
green   = '#83d2e4'
yellow  = '#b2cbd1'
blue    = '#bdc5eb'
magenta = '#83d2e4'
cyan    = '#b2cbd1'
white   = '#dee3e5'
